### ISSUE TITLE
facing issue while trying to setup OCATS

### ISSUE THREAD

**Issue by Sayanava** [Comcast/cats#11]
Hi,

I have been trying to do the setup for OCATS following the install and build guide uploaded(which seems to be a bit older one where now many dependencies have changed or updated,like for example  use of httpd,whereas presently we have implemenation of "apache2" instead of "httpd",so,where we can configure the AJP proxies or video storage in apache2 unlike "httpd").For YAML Configuration Files,in the master branch,we dont have anything like "settops.catsrack" which is needed.While deploying the .ear or .war files,getting issue as:

[standalone@localhost:9999 /] deploy /home/xyz/cats/Comcast-cats-6206b1c/services/video-recorder/war/target/video-recorder-service.war
{"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.persistenceunit.\"video-recorder-service.war#pvr-persistence-unit\"jboss.naming.context.java.jboss.cats.datasources.pvrMissing[jboss.persistenceunit.\"video-recorder-service.war#pvr-persistence-unit\"jboss.naming.context.java.jboss.cats.datasources.pvr]"]}}} .

Request your help on the above issues I am facing presently,and probably some update on the install doc will be helpful.

Thanks

**Comment by sajayjk** [comment]
Have you added the pvr_db datasource in your standalone(-full).xml? Also ensure that pvr_db exists in mysql. A blank db is enough. The service will update the tables.

                <datasource jta="true" jndi-name="java:jboss/cats/datasources/pvr" pool-name="pvr-ds" enabled="true" use-ccm="false">
                    <connection-url>jdbc:mysql://localhost:3306/pvr_db</connection-url>
                    <driver-class>com.mysql.jdbc.Driver</driver-class>
                    <driver>com.mysql</driver>
                    <transaction-isolation>TRANSACTION_READ_COMMITTED</transaction-isolation>
                    <pool>
                        <min-pool-size>10</min-pool-size>
                        <max-pool-size>100</max-pool-size>
                        <prefill>true</prefill>
                    </pool>
                    <security>
                        <user-name>dbuser</user-name>
                        <password>dbpasswd</password>
                    </security>
                    <validation>
                        <validate-on-match>false</validate-on-match>
                        <background-validation>false</background-validation>
                    </validation>
                    <statement>
                        <share-prepared-statements>false</share-prepared-statements>
                    </statement>
                </datasource>

**Comment by Sayanava** [comment]
![page1](https://cloud.githubusercontent.com/assets/6228092/9808272/6334c1c8-587b-11e5-9ff3-4d5394943857.png)
![page2](https://cloud.githubusercontent.com/assets/6228092/9808277/6c40783e-587b-11e5-9a35-7d1944c43a2d.png)
![page3](https://cloud.githubusercontent.com/assets/6228092/9808281/72e7e4ba-587b-11e5-97f8-bff35a4f0634.png)
![page4](https://cloud.githubusercontent.com/assets/6228092/9808285/787c3ff2-587b-11e5-9759-370bdc5de7ba.png)

Please find above the screenshots of my : "/opt/ocats/software/jboss/current/standalone/configuration/standalone-full.xml" containing the changes mentioned.
The file  "/opt/ocats/software/jboss/current/standalone/configuration/standalone-full.xml" as a whole is uploaded in the following location for your reference : 
http://s000.tinyupload.com/?file_id=26543712554956655583 
& the mysql database content is:
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| keymanager         |
| mysql              |
| performance_schema |
| pvr_db             |
+--------------------+
5 rows in set (0.00 sec)

mysql> use pvr_db
Database changed
mysql> show tables;
Empty set (0.00 sec)

mysql> use keymanager;
Database changed
mysql> show tables;
+----------------------+
| Tables_in_keymanager |
+----------------------+
| key_code_format      |
| key_codes            |
| key_layout           |
| remote_type          |
+----------------------+
4 rows in set (0.00 sec)

While trying to deploy .war and .ear files,I get the issue as metioned earlier and it throws error for : 
[standalone@localhost:9999 /] deploy <pathTO>/ocats-master-ear-<version>.ear
[standalone@localhost:9999 /] deploy <pathTO> /video-recorder-service.war 

Please find below the screenshot of the error messages I am getting while using deploy:
![ocats-master-ear](https://cloud.githubusercontent.com/assets/6228092/9808928/7f020a68-5881-11e5-9f00-31fdd784caf6.png)
![video-recorder-service](https://cloud.githubusercontent.com/assets/6228092/9808938/878d7384-5881-11e5-821a-366efd8ea29a.png)

Whereas,as mentioned in the install doc,I dont see the following files in my workspace to deploy:-
[standalone@localhost:9999 /] deploy <pathTO>/ocats-ui.war
[standalone@localhost:9999 /] deploy <pathTO>/ROOT.war root.war redirects to ocats Ui.

I am using jboss-as-7.1.1.Final.

Request your help on this.Thanks.

**Comment by sajayjk** [comment]
Please create separate issues for different issues/questions.

With regards to the pvr_db issue, your standalone-full.xml does not contain the definition to the mysql driver. 

You must have something like the below (modify it as required, as per the mysql module you may installed on your Jboss).

<driver name="com.mysql" module="com.mysql">
 <xa-datasource-class>com.mysql.jdbc.jdbc2.optional.MysqlXADataSource</xa-datasource-class>
</driver>

**Comment by Sayanava** [comment]
Thanks a lot Sajay.There was some issues related to MySQL privileges.Able to deploy video-recorder-service.war and ocats-master-ear-.ear successfully now.
