### ISSUE TITLE
queries related to OCATS setup

### ISSUE THREAD

**Issue by Sayanava** [Comcast/cats#13]
Hi Sajay,
We have few queries related to OCATS setup from the the install doc:-

1)In th YAML Configuration Files portion,
the checked-out code don't have "settops.catsrack" inside /ocats-release/sampleConfigFiles whereas it is present inside ocats-config/war/src/test/resources.Which one we are supposed to use? 

2)In the Deploy .war and .ear Files portion,
[standalone@localhost:9999 /] deploy <pathTO>/ocats-ui.war
[standalone@localhost:9999 /] deploy <pathTO>/ROOT.war root.war redirects to ocats Ui
We don't see ocats-ui.war or ROOT.war getting generated anywhere.
Do we need to deploy OCATS.war instead OR any other specific .war file?

Request your help on this.

**Comment by sajayjk** [comment]
Hi Sayanava,
1) You need not place settops.catsrack. It will be auto generated and maintained by the code.
I'll shall check and update the documentation surrounding this. 
(In case settops.cats.rack is not auto generated you may create a blank file with that name).

2) You are right here. OCATS.war should be used. I'll update the documentation surrounding this.
ROOT.war is just to auto redirect to the main application. You can do this via httpd rewrite or proxy rules as well. I'll remove the documentation regarding ROOT.war.

**Comment by sajayjk** [comment]
Updated documentation cafe317a40e433a9f5016e23f08f22d916b17ca4
