### ISSUE TITLE
test the OCATS installation setup

### ISSUE THREAD

**Issue by Sayanava** [Comcast/cats#15]
Hi Sajay,
According to the OCATS_INSTALL_GUIDE,we are done deploying the 3 mentioned .war and .ear files successfully with the status as:-
[standalone@localhost:9999 /] deployment-info --name=OCATS.war
NAME      RUNTIME-NAME PERSISTENT ENABLED STATUS 
OCATS.war OCATS.war    true       true    OK     

[standalone@localhost:9999 /] deployment-info --name=video-recorder-service.war             
NAME                       RUNTIME-NAME               PERSISTENT ENABLED STATUS 
video-recorder-service.war video-recorder-service.war true       true    OK     

[standalone@localhost:9999 /] deployment-info --name=ocats-master-ear-1.1-OCATS-SNAPSHOT.ear
NAME                                    RUNTIME-NAME                            PERSISTENT ENABLED STATUS 
ocats-master-ear-1.1-OCATS-SNAPSHOT.ear ocats-master-ear-1.1-OCATS-SNAPSHOT.ear true       true    OK 

After this,can you please suggest some steps on how we can go ahead to verify the installation setup done(to check whether its correct or not), by using some sample test examples.

Request your help on this.

**Comment by Sayanava** [comment]
Hi,

After doing the deployment,we are able to hit the different web-services offered like for example when we try "http://localhost:8080/snmp-service/",it gives us the output as " Cats snmp module is up and running!".Does that suggest our server is ok?.Can u please suggest some sample test classes for example and steps,ways to verify our setup done here.

Request your help on this.

**Comment by sajayjk** [comment]
Try to access http://localhost:8080/CATS (if hosted on localhost:8080).
This should bring up the web ui where you can go ahead and add/remove settop information.

Please check that the rackconfig.catsrack is modified to reflect the rack you have in place.

**Comment by Sayanava** [comment]
Hi Sajay,
We are able to see the web ui by hitting on http://localhost:8080/CATS where we can see settop information getting listed.Thanks.

It will be helpful if you can kindly provide some documentation having the details of different web services offered and their usage details.

Request help on this.

**Comment by Sayanava** [comment]
Hi,
Can you please let us know on different types of web-services OCATS has in offering and their usage.Any document or note on the same will be helpful.
Request help on this.
Thanks.

**Comment by sajayjk** [comment]
Working on this.

**Comment by sajayjk** [comment]
Please check the getting started guide at https://github.com/Comcast/cats/blob/master/docs/OCATS%20Getting_Started_GUIDE.doc 

Currently the only services available are IR, Power and SNMP
and currently they are all SOAP based.

Finally API docs are also available in the docs folder

**Comment by sajayjk** [comment]
The WSDL for the services are available at 
http://<host>/ir-service/IRService?wsdl
http://<host>/power-service/PowerService?wsdl
http://<host>/snmp-service/SnmpService?wsdl
