### ISSUE TITLE
Problem running standalone.sh file

### ISSUE THREAD

**Issue by Fathimasyfa** [Comcast/cats#18]
Hi,

After adding all the changes to the standalone-full.xml file when i run standalone.sh i face controller Boot thread issue.It neither gives any ERROR nor moves further,It just gets paused.I googled and it said to check for the ports.everything is fine .I even get the home page of jboss AS7 when i tried localhost:8080, but i dont find jboss running.why?
I have attached a screenshot of this.
![issue](https://cloud.githubusercontent.com/assets/15026208/10386120/68f4d3cc-6e70-11e5-9175-3873581f50d5.png)

**Comment by sajayjk** [comment]
Looks like Jboss started properly as per your screenshot.
The issue is you may have not edited your Jboss conf file to use standalone-full.xml . As per the screenshot, its using standalone.xml. Please check Jboss documentation for info on how to do this.
