### ISSUE TITLE
Loading a new Remote Control keys into the OCATS Rack

### ISSUE THREAD

**Issue by ivanherrera402** [Comcast/cats#2]
In the OCATS Rack. We are trying to add a new remote control for a STB that is not Motorola or SA.
After recording the keys using the RedRat SignalDButil and following the instructions to load it in the OCATS, it did not work. In the keymanager-service gui (web page), going to the Remotes tab and select Add, it gives the following error:

type Exception report

message

description The server encountered an internal error () that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: viewId:/listRemotes.jsf - View /listRemotes.jsf could not be restored.
javax.faces.webapp.FacesServlet.service(FacesServlet.java:606)
org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62)

root cause

javax.faces.application.ViewExpiredException: viewId:/listRemotes.jsf - View /listRemotes.jsf could not be restored.
com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:205)
com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:116)
com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62)

note The full stack trace of the root cause is available in the JBoss Web/7.0.13.Final logs."

The suggested workaround to rename an existing remote with the newly loaded remote did not work either.

As of now there is no way to add a new remote to the CATS rack.

ivan.herrera@arris.com
(ARRIS)

**Comment by cfrede001** [comment]
Team is investigating and will provide feedback.

**Comment by sajayjk** [comment]
Created a patch fix for this.
9c2edb9593dff8cdb51c428e7d052e213eb7f4ae 

Please perform a pull and build keymanager-service.

Navigate to services/ir/keymanager and do a 'mvn clean install'

This will generate the keymanager-service.war. 
Build the master ear again and deploy.

**Comment by ivanherrera402** [comment]
Ccing  John

**Comment by sajayjk** [comment]
Please let us know if this fixes your issue.

Also, the exception provided in the issue above is not the actual problem.
The above exception just means the view expired. A page reload will solve the issue.

**Comment by ivanherrera402** [comment]
Adding john this time

From: Herrera, Ivan
Sent: Tuesday, June 30, 2015 1:43 PM
To: 'Comcast/cats'; Comcast/cats
Subject: RE: [cats] Loading a new Remote Control keys into the OCATS Rack (#2)

Ccing  John

**Comment by sajayjk** [comment]
Finally, when using the SignalDBUtility while recording keys, please make sure the key names correspond to keys described in the [RemoteCommand](https://github.com/Comcast/cats/blob/master/apis/settop/src/main/java/com/comcast/cats/RemoteCommand.java) enum. Random key names will not work while using CATSVision.

**Comment by ivanherrera402** [comment]
From: Diaz, John 
Sent: Tuesday, June 30, 2015 2:38 PM
To: sajayjk@tataelxsi.co.in; Frederick, Chad
Cc: Herrera, Ivan; Diaz, John
Subject: RE: [cats] Loading a new Remote Control keys into the OCATS Rack (#2)

Sajay:
Can you send instruction on how to do the pull 
“Please perform a pull “
and once it is done, how can I build the keymanager-service.

and build keymanager-service.
Navigate to services/ir/keymanager and do a 'mvn clean install'
This will generate the keymanager-service.war. 

How can I do this?
Build the master ear again and deploy. 


Thanks in advance for your response.

John

**Comment by johndiaz2** [comment]
Sajay:
When you say "Finally, when using the SignalDBUtility while recording keys, please make sure the key names correspond to keys described in the RemoteCommand enum. Random key names will not work while using CATSVision." means if the command in the remote is not present in this file it will need to be added?  What steps do I need to take for the updated version of this file to be active in the server?  Do I need to stop and start the RedRat (IR) servise?

Thanks,

**Comment by sajayjk** [comment]
When using the SignalDBUtility you specify a name for each key that is to be recorded. Just need to make sure that the name provided is one of the keys in that RemoteCommand enum.

**Comment by sajayjk** [comment]
I have added a [wiki page](https://github.com/Comcast/cats/wiki/Adding-a-new-Remote.-|-OCATS-1.0)  highlighting the tasks required to add a new remote to CATS.

**Comment by ivanherrera402** [comment]
Thanks for the adding the remote instructions. Just in case, going to mention it again, but we also are still waiting for  instructions regarding John's email.
1) Can you send instruction on how to do the pull
“Please perform a pull “
2) and once it is done, how can I build the keymanager-service.

and build keymanager-service.
Navigate to services/ir/keymanager and do a 'mvn clean install'
This will generate the keymanager-service.war.

3)  How can I do this?
Build the master ear again and deploy.
