### ISSUE TITLE
Operation handler failed to complete & New missing/unsatisfied dependencies: service jboss.jdbc-driver.com_mysql

### ISSUE THREAD

**Issue by Babubsp** [Comcast/cats#21]
Hi,

Anyone faced this issues and found a solution means please replay to this.. struggling for long period.

10:29:58,456 INFO  [org.jboss.as.server] (HttpManagementService-threads - 1) JBAS015870: Deploy of deployment "keymanager-service.war" was rolled back with failure message JBAS014750: Operation handler failed to complete

JBAS014775:    New missing/unsatisfied dependencies:
      service jboss.jdbc-driver.com_mysql (missing) dependents: [service jboss.data-source.java:/keymanager, service jboss.data-source.java:/pvr]

**Comment by cfrede001** [comment]
You're probably missing the Mysql JDBC module installation for your JBoss 7 instance.
https://developer.jboss.org/wiki/DataSourceConfigurationInAS7
https://docs.jboss.org/author/display/AS7/Admin+Guide#AdminGuide-JDBCDriverInstallation

**Comment by Babubsp** [comment]
Thank You cfrede001... as your response for my question its mysql driver problem only.... 
Now the error is not repeating...

thanks once again.... :)
