### ISSUE TITLE
OCATS installation Issue - Error while executing Maven comments and deploying .war/.ear files

### ISSUE THREAD

**Issue by LTComcast** [Comcast/cats#28]
We are working on the installation of OCATS. We are facing some issue during installation. Please find the below issues observed during installation.

Issue 1:

We are able to install Maven successfully. But after issuing  "mvn clean install -P webstar" cmd below error was observed.

[root@ocatsserver ocats-vision]# mvn clean install -P webstart
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'parent.relativePath' of POM com.comcast.cats:ocats-release:1.0-OCATS (/root/Downloads/OCATS/ocats-vision/pom.xml) points at com.comcast.cats:ocats-project instead of com.comcast.cats:superpom-ocats, please verify your project structure @ line 31, column 10
[FATAL] Non-resolvable parent POM for com.comcast.cats:ocats-release:1.0-OCATS: Failure to find com.comcast.cats:superpom-ocats:pom:1.0-OCATS in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 31, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project com.comcast.cats:ocats-release:1.0-OCATS (/root/Downloads/OCATS/ocats-vision/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for com.comcast.cats:ocats-release:1.0-OCATS: Failure to find com.comcast.cats:superpom-ocats:pom:1.0-OCATS in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 31, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

Issue: 2:

Deploying 'video-recorder-service ' and  'ocats-master-ear-1.0-OCATS ' files into AS7 was unsuccessful.Please find the attached files for the same,

[Deploy_Error.zip](https://github.com/Comcast/cats/files/317861/Deploy_Error.zip)

**Comment by sajayjk** [comment]
You will have to build the parent superpom first.
Go to the superpom filder and run a `mvn clean install`

**Comment by sajayjk** [comment]
Please create a separate issue for issue #2. 
Thanks.
