### ISSUE TITLE
Settop Config File not available and could not be created null/settops.catsrack

### ISSUE THREAD

**Issue by sjsauto** [Comcast/cats#35]
I am getting the below error while loading Rack configuration.  Can you please help.  I have copied all the configuration under /var/www/html/cats/config/ location.

16:20:59,550 ERROR [com.comcast.cats.config.ui.RackServiceImpl] (http--10.23.157.22-8080-6) Rack YAML file missing at null/rackconfig.catsrack and could not be created
16:20:59,552 ERROR [stderr] (http--10.23.157.22-8080-6) java.io.IOException: No such file or directory
16:20:59,552 ERROR [stderr] (http--10.23.157.22-8080-6)         at java.io.UnixFileSystem.createFileExclusively(Native Method)
16:20:59,553 ERROR [stderr] (http--10.23.157.22-8080-6)         at java.io.File.createNewFile(File.java:1006)
16:20:59,553 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.comcast.cats.service.util.YAMLUtils.loadFromYAML(YAMLUtils.java:67)
16:20:59,554 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.comcast.cats.config.ui.RackServiceImpl.readRacksFromDisk(RackServiceImpl.java:89)
16:20:59,554 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.comcast.cats.config.ui.RackServiceImpl.refresh(RackServiceImpl.java:140)
16:20:59,555 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.comcast.cats.config.ui.RackController.refresh(RackController.java:124)
16:20:59,555 ERROR [stderr] (http--10.23.157.22-8080-6)         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:20:59,556 ERROR [stderr] (http--10.23.157.22-8080-6)         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
16:20:59,556 ERROR [stderr] (http--10.23.157.22-8080-6)         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:20:59,556 ERROR [stderr] (http--10.23.157.22-8080-6)         at java.lang.reflect.Method.invoke(Method.java:606)
16:20:59,557 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.el.parser.AstValue.invoke(AstValue.java:262)
16:20:59,557 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:278)
16:20:59,558 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.jboss.weld.util.el.ForwardingMethodExpression.invoke(ForwardingMethodExpression.java:39)
16:20:59,558 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.jboss.weld.el.WeldMethodExpression.invoke(WeldMethodExpression.java:50)
16:20:59,559 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
16:20:59,559 ERROR [stderr] (http--10.23.157.22-8080-6)         at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:88)
16:20:59,560 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
16:20:59,560 ERROR [stderr] (http--10.23.157.22-8080-6)         at javax.faces.component.UICommand.broadcast(UICommand.java:315)
16:20:59,562 ERROR [stderr] (http--10.23.157.22-8080-6)         at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:794)
16:20:59,564 ERROR [stderr] (http--10.23.157.22-8080-6)         at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1259)
16:20:59,565 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:81)
16:20:59,565 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
16:20:59,566 ERROR [stderr] (http--10.23.157.22-8080-6)         at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
16:20:59,567 ERROR [stderr] (http--10.23.157.22-8080-6)         at javax.faces.webapp.FacesServlet.service(FacesServlet.java:593)
16:20:59,568 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:329)
16:20:59,568 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
16:20:59,569 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.jboss.weld.servlet.ConversationPropagationFilter.doFilter(ConversationPropagationFilter.java:62)
16:20:59,569 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:280)
16:20:59,570 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:248)
16:20:59,571 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:275)
16:20:59,571 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:161)
16:20:59,572 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.jboss.as.web.security.SecurityContextAssociationValve.invoke(SecurityContextAssociationValve.java:153)
16:20:59,573 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
16:20:59,578 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
16:20:59,579 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
16:20:59,579 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:368)
16:20:59,580 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:877)
16:20:59,582 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:671)
16:20:59,582 ERROR [stderr] (http--10.23.157.22-8080-6)         at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:930)
16:20:59,583 ERROR [stderr] (http--10.23.157.22-8080-6)         at java.lang.Thread.run(Thread.java:745)
16:20:59,584 ERROR [com.comcast.cats.config.ui.SettopSlotConfigServiceImpl] (http--10.23.157.22-8080-6) Settop Config File not available and could not be created null/settops.catsrack  No such file or directory
16:25:00,029 INFO  [com.comcast.cats.service.ir.redrat.RedRatManagerImpl] (EJB default - 3) RedRatManager refresh

**Comment by XsubinX** [comment]
Refer this thread https://github.com/Comcast/cats/issues/29

**Comment by sjsauto** [comment]
Hi Subin, 

  I have followed the steps which you have provided in the link.  I don't see any issues with the deployment and all three wars are being deployed properly. 

But when I try to open  http://10.23.157.22:8080/CATS/rack/List.xhtml url I get the below error. 

**13:27:42,706 ERROR [com.comcast.cats.config.ui.RackServiceImpl] (http--10.23.157.22-8080-6) Rack YAML file missing at null/rackconfig.catsrack and could not be created**

I am not sure, why its trying to refer to   null/rackconfig.catsrack location. 

In my standalone-full.xml I have configured the location to  /var/www/html/cats/config"

Could you please suggest if there is anything else which i am missing here ?

**Comment by sjsauto** [comment]
Closing this ticket, I update the property to cats.config.path from prod.cats.config.path and it working now. 

Thanks.
