### ISSUE TITLE
Issue adding New Remote Control.

### ISSUE THREAD

**Issue by sjsauto** [Comcast/cats#37]
Hi,

   Request help in below issue, I am trying to add a new remote based on the instruction which were provide under https://github.com/Comcast/cats/wiki/Adding-a-new-Remote.-%7C-OCATS-1.0 link but I get the below error message. 

Could please provide any inputs on how this could be solved ? I am using IRNetbox-111. 

![image](https://cloud.githubusercontent.com/assets/22946767/20729369/8d0dc1a6-b636-11e6-8642-3865c6d60f56.png)

**Comment by sajayjk** [comment]
Is the IR device configured in rackList.yml and settopList.yml show irnetbox as the ir device. The screenshot suggests it still shows GC100.

**Comment by sjsauto** [comment]
Thanks Sajay, 

I have updated the IR device configuration name in rackconfig.catsrack, but it gives me the below error. Is there any where else I need to update the IR device details ? 

![image](https://cloud.githubusercontent.com/assets/22946767/20776537/08db7dac-b716-11e6-9e04-cf9dc95a9589.png)

**Comment by sjsauto** [comment]
Thanks Sajay. 

I have updated the irnet details in the configuration file but I continue to get the below error. Any other configuration which needs to be done for IRDNETBOX. ?

![image](https://cloud.githubusercontent.com/assets/22946767/20776935/6cc089f0-b718-11e6-9210-00215dfaa5c9.png)

**Comment by sajayjk** [comment]
Did you add the device info and the hub info into keymanager?
http://localhost:8080/keymanager-service/ 

There should be a tab to add the redrathub info and another tab to enter details of the Irnetbox

**Comment by sajayjk** [comment]
Also do you have the redrathub installed on the server?

**Comment by sjsauto** [comment]
Hi Sajay, 

       I have already updated the details in below link. 

![image](https://cloud.githubusercontent.com/assets/22946767/20805122/5a9bd0e4-b7aa-11e6-8bfa-f004077af192.png)

![image](https://cloud.githubusercontent.com/assets/22946767/20805137/6a8fda0e-b7aa-11e6-8708-e67d5ed22107.png)

I have also install the redrathub on the same server. I see while the Jboss while starting it is able to detect the IRNET device. 

 
![image](https://cloud.githubusercontent.com/assets/22946767/20805190/9c83a950-b7aa-11e6-8d2a-9cce97aced95.png)

Please find the screenshot of the Redhub started. 

![image](https://cloud.githubusercontent.com/assets/22946767/20805306/ed5b13d6-b7aa-11e6-9b5f-7ef58f654928.png)

![image](https://cloud.githubusercontent.com/assets/22946767/20805398/5e1b2a5c-b7ab-11e6-94a8-897ebead327c.png)

Anything else which I am missing here ?

**Comment by sajayjk** [comment]
Can you also show how the settop is configured. In the UI can you copy paste screen shots of teh settop listing page and the rack listing page.

**Comment by sjsauto** [comment]
Please find the screenshot below

![image](https://cloud.githubusercontent.com/assets/22946767/20805923/9ffa0c0c-b7ad-11e6-8600-da694ab69cbd.png)

![image](https://cloud.githubusercontent.com/assets/22946767/20805937/b09feb62-b7ad-11e6-8b7b-2bb25514a3fd.png)


![image](https://cloud.githubusercontent.com/assets/22946767/20805972/d4c04672-b7ad-11e6-8420-a5a5f30c4b05.png)

![image](https://cloud.githubusercontent.com/assets/22946767/20805987/e8f9a412-b7ad-11e6-8c82-39551b76bfc2.png)

**Comment by sajayjk** [comment]
The device IP in the yml file for IR show 127.0.0.1.. it should reflect the IP of teh irnetbox which I guess is 192.168.1.113 in your case

**Comment by sjsauto** [comment]
Thanks Sajay, after updating the IP it going through, but I am getting a dataset issue. 

![image](https://cloud.githubusercontent.com/assets/22946767/20811203/a7cedb06-b7c1-11e6-9b52-ade70a58a06f.png)


I have updated the same in the Key-manager-service url link.

![image](https://cloud.githubusercontent.com/assets/22946767/20811258/d30f390a-b7c1-11e6-944e-c37e77c83b0a.png)

Please find the xml file which I am using below. 

![image](https://cloud.githubusercontent.com/assets/22946767/20811389/5739b7b4-b7c2-11e6-80e5-381b97161c0b.png)

![image](https://cloud.githubusercontent.com/assets/22946767/20811408/6aeffa98-b7c2-11e6-985f-16d240896d9f.png)

**Comment by cfrede001** [comment]
Did you restart the RedRatHub after adding the updated xml keyset?

**Comment by sjsauto** [comment]
yes, I tried that as well, I still get the above error.

**Comment by cfrede001** [comment]
Did you perform the telnet and verify that it is in the dataset?

**Comment by sajayjk** [comment]
Also when you start redrathub you must point to this xml. By default it points to the default xml that is provided with CATS.

**Comment by sjsauto** [comment]
Thanks for your inputs. i dont see the error any more.  But I dont see the Ui change on the STB, I will recheck on the signal which was captured and update you. 

Thanks for your inputs.

**Comment by sjsauto** [comment]
Thanks a lot for your support, its working for me now.

**Comment by sajayjk** [comment]
Great
