### ISSUE TITLE
Java 8 CATS Vision

### ISSUE THREAD

**Issue by ivanherrera402** [Comcast/cats#6]
I currently have Java version 8 installed on my laptop. I can get to the App but when I click on the monitor icon in the CV column  a pop up(JNLP file) displays. I select Open with and click on the OK button. I then get the following pop up(Application Blocked by Java Security.)"For security, applications must now meet the requirements for the High or Very High security settings, or be part of the Exception Site List, to be allowed to run. So my Exception Site List I have the following entry http://10.10.149.65:8080.   I still cannot see the video stream for my stb. 
I remember Sree telling us that yo have to run Java 7
Do you really need Java 7 in order for the the Vision Application to work? I really do not want to downgrade since other projects I work on require the latest Java. Are you guys in the process of fixing this limitation? If not or if not in the near future, is there a way to bounce between Java 7 & Java 8 on my labtop effortlessly?

Ivan

**Comment by sajayjk** [comment]
We have currently tested on Java 7 platform. 
To use CATSVision, you have to be running Java 7. After installing JAVA 7 navigate to Control Panel, Search for Java, click on the securities tab and select Medium as your security level for Java applications.

We are fixing the security issues and that will be available in our next release.
