### ISSUE TITLE
The Power device gives an Error status 500 

### ISSUE THREAD

**Issue by ivanherrera402** [Comcast/cats#7]
Issue: Power Commands of Power device not working.

When in VISION application, whenever you press any of the following Hard Power Commands( OFF REBOOT, ON) on the top part of the virtual remote control
the following 500 error is thrown: 

2015/06/16 04:30:02 PM EDT : Selected settop - 00:1F:C4:D6:4C:CB
2015/06/16 04:30:06 PM EDT : Power Key pressed for Settop -  00:1F:C4:D6:4C:CB[ Key = Reboot]
2015/06/16 04:30:07 PM EDT : Error Occurred for settop '00:1F:C4:D6:4C:CB'-javax.xml.ws.soap.SOAPFaultException: Error status 500 Internal Server Error returned
2015/06/16 04:34:54 PM EDT : Remote Key pressed for Settop -  00:1F:C4:D6:4C:CB[ Action Type = PRESS, Key = POWER]
2015/06/16 04:35:01 PM EDT : Remote Key pressed for Settop -  00:1F:C4:D6:4C:CB[ Action Type = PRESS, Key = POWER]
2015/06/16 04:35:20 PM EDT : Power Key pressed for Settop -  00:1F:C4:D6:4C:CB[ Key = Off]
2015/06/16 04:35:20 PM EDT : Error Occurred for settop '00:1F:C4:D6:4C:CB'-javax.xml.ws.soap.SOAPFaultException: Error status 500 Internal Server Error returned
2015/06/16 04:35:20 PM EDT : Power Key pressed for Settop -  00:1F:C4:D6:4C:CB[ Key = On]
2015/06/16 04:35:20 PM EDT : Error Occurred for settop '00:1F:C4:D6:4C:CB'-javax.xml.ws.soap.SOAPFaultException: Error status 500 Internal Server Error returned

**Comment by sajayjk** [comment]
Hi Ivan, 

I would want some more info to start debugging the issue.
To start with, please let me know what power device you have racked? 
Is it a NPS-16

**Comment by ivanherrera402** [comment]
Sajay,

Yes it is the NPS16 - WTI
[Close this window]

Please let me know what other info you need.

Thanks,

Ivan

**Comment by sajayjk** [comment]
Also please share me your rackconfig.catsrack file and settops.catsrack files.
You may mail it to me, if you dont want to attach it here.

**Comment by sajayjk** [comment]
Hi Ivan,
I will also want the jboss log file. 
The jboss log file can be found by logging into the CATS linux server where Jboss is installed. I’m not too sure in which directory Jboss is installed in that server but lets say it is /opt/software/jboss/. 
The log file will be available at opt/software/jboss/standalone/log.
Please send me server.log that contains todays log. (Hope that you tried power today so that the error message is seen in this log).

This much will help me start analyzing the issue and check whats happening.

Again, you mail it to me, if you dont want it attached here.

Regards
Sajay jK

**Comment by ivanherrera402** [comment]
Sajay,

  Attached the configs you asked for separately and zipped just in case.

If you cannot open either let me know a dropbox location were I can stage them.

Thanks,

Ivan

**Comment by ivanherrera402** [comment]
Sajay,

I found it here. So hopefully this is what you were wanting. We also ran the test today.

/opt/ocats/software/jboss/jboss-as-7.1.1.Final/standalone/log/server.log

**Comment by sajayjk** [comment]
Yes. Thats the one.
________________________________________

**Comment by sajayjk** [comment]
Fixed in commit https://github.com/Comcast/cats/commit/7e37a69577acfb69211da964992289fd13e0d21d
